# Generated by Django 3.2 on 2022-10-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
