# Generated by Django 4.2.13 on 2024-05-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacker", "0003_project_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
