# Generated by Django 4.2.13 on 2024-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacker", "0004_feature_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
